### PR TITLE
Update `wp-fork` to version `2.3.2`

### PR DESCRIPTION
**Pull request by fluiddot**
This PR updates the `wp-fork` branch with upstream version `2.3.2` and applies the required changes to publish the Android library associated with the package.

Since the PR contains a massive amount of changed files, in order to review this PR, it's better to compare the branch with the upstream repository and validate that we apply the same changes we have in `wp-fork`:
- [Changes applied on top of the `2.3.2` version of upstream repository](https://github.com/software-mansion/react-native-gesture-handler/compare/2.3.2...wordpress-mobile:wp-fork-2.3.2)
- [Changes applied in `wp-fork`](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/2)

**NOTE:** Once this PR is ready, we should also merge https://github.com/wordpress-mobile/react-native-gesture-handler/pull/19 so the diff showed in `wp-fork` doesn't contain the `2.3.2` version changes.

## Testing instructions
1. Apply the following patch to the [Gutenberg project](https://github.com/WordPress/gutenberg):
```diff
diff --git a/packages/react-native-editor/android/app/build.gradle b/packages/react-native-editor/android/app/build.gradle
index a75a855cd7990a6813405c00e04b2ea45456ac8d..6a7b6ecadd60b540eaa082737a517ccd53c1365b 100644
--- a/packages/react-native-editor/android/app/build.gradle
+++ b/packages/react-native-editor/android/app/build.gradle
@@ -186,7 +186,7 @@ dependencies {
     implementation "com.github.wordpress-mobile:react-native-slider:${extractPackageVersion(packageJson, '@react-native-community/slider', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-get-random-values:${extractPackageVersion(packageJson, 'react-native-get-random-values', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-masked-view:${extractPackageVersion(packageJson, '@react-native-masked-view/masked-view', 'dependencies')}"
-    implementation "com.github.wordpress-mobile:react-native-gesture-handler:${extractPackageVersion(packageJson, 'react-native-gesture-handler', 'dependencies')}"
+    implementation 'com.github.wordpress-mobile:react-native-gesture-handler:wp-fork-2.3.2-SNAPSHOT'
     implementation "org.wordpress-mobile:react-native-screens:${extractPackageVersion(packageJson, 'react-native-screens', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-safe-area-context:${extractPackageVersion(packageJson, 'react-native-safe-area-context', 'dependencies')}"
     implementation "com.github.wordpress-mobile:react-native-reanimated:${extractPackageVersion(packageJson, 'react-native-reanimated', 'dependencies')}"
diff --git a/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java b/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java
index d74315aba221a2444181d6677e15d60980306a48..b94e581a736cbe1bf6f05bc338b448a889eb89a8 100644
--- a/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java
+++ b/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java
@@ -37,7 +37,7 @@ import com.facebook.react.ReactPackage;
 import com.facebook.react.shell.MainReactPackage;
 import com.facebook.soloader.SoLoader;
 import com.reactnativecommunity.webview.RNCWebViewPackage;
-import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
+import com.swmansion.gesturehandler.RNGestureHandlerPackage;
 import com.swmansion.reanimated.ReanimatedJSIModulePackage;
 import com.swmansion.reanimated.ReanimatedPackage;
 import com.swmansion.rnscreens.RNScreensPackage;
diff --git a/packages/react-native-bridge/android/react-native-bridge/build.gradle b/packages/react-native-bridge/android/react-native-bridge/build.gradle
index a55491b687660565098361c00d02b20d4dd52663..6c9930ece54cf909a385b792655513522a420e5b 100644
--- a/packages/react-native-bridge/android/react-native-bridge/build.gradle
+++ b/packages/react-native-bridge/android/react-native-bridge/build.gradle
@@ -70,7 +70,7 @@ dependencies {
     implementation "com.github.wordpress-mobile:react-native-slider:${extractPackageVersion(packageJson, '@react-native-community/slider', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-get-random-values:${extractPackageVersion(packageJson, 'react-native-get-random-values', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-masked-view:${extractPackageVersion(packageJson, '@react-native-masked-view/masked-view', 'dependencies')}"
-    implementation "com.github.wordpress-mobile:react-native-gesture-handler:${extractPackageVersion(packageJson, 'react-native-gesture-handler', 'dependencies')}"
+    implementation 'com.github.wordpress-mobile:react-native-gesture-handler:wp-fork-2.3.2-SNAPSHOT'
     implementation "org.wordpress-mobile:react-native-screens:${extractPackageVersion(packageJson, 'react-native-screens', 'dependencies')}"
     implementation "org.wordpress-mobile:react-native-safe-area-context:${extractPackageVersion(packageJson, 'react-native-safe-area-context', 'dependencies')}"
     implementation "com.github.wordpress-mobile:react-native-reanimated:${extractPackageVersion(packageJson, 'react-native-reanimated', 'dependencies')}"
```
2. Build the Gutenberg demo app (i.e. `packages/react-native-editor/android` project).
3. Observe that the project can be built without errors.
4. Run the Gutenberg demo app and observe that works as expected.

### CODE REVIEW

**Comment by geriux** [comment]
Hey @fluiddot 👋 

I tried to test this using the patch but it looks like it only works if there's no Reanimated / Gesture Handler code being rendered.

If there's some Reanimated / Gesture handler code being rendered It crashes with the following error

`java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Double`

Maybe I'm missing something 😅

**Comment by fluiddot** [comment]
> I tried to test this using the patch but it looks like it only works if there's no Reanimated / Gesture Handler code being rendered.
> 
> If there's some Reanimated / Gesture handler code being rendered It crashes with the following error
> 
> `java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Double`
> 
> Maybe I'm missing something 😅

@geriux oh, that's probably caused by using a different version on the JS side, actually, I think I forgot to add to the patch [the reference change to the dependency in the `package.json`](https://github.com/WordPress/gutenberg/blob/ca463dbc995e7be3bb2f109b4b656ca09bbba92f/packages/react-native-editor/package.json#L60). `react-native-gesture-handler` package should point to the tarball generated in this PR:
```
"react-native-gesture-handler": "https://raw.githubusercontent.com/wordpress-mobile/react-native-gesture-handler/wp-fork-2.3.2/react-native-gesture-handler-2.3.2-wp-1.tgz",
```

**Review by geriux — APPROVED** [review]
LGTM!

**Comment by fluiddot** [comment]
@geriux heads up that I'm going to put the merge on hold until I open a PR in Gutenberg to update this dependency. I'll let you know when it's ready.

Once that PR is ready to merge, we could start merging the different PRs.

**Comment by geriux** [comment]
> @geriux heads up that I'm going to put the merge on hold until I open a PR in Gutenberg to update this dependency. I'll let you know when it's ready.

Sounds good! 👍

**Comment by fluiddot** [comment]
> @geriux heads up that I'm going to put the merge on hold until I open a PR in Gutenberg to update this dependency. I'll let you know when it's ready.
> 
> Once that PR is ready to merge, we could start merging the different PRs.

@geriux  I created [this PR](https://github.com/WordPress/gutenberg/pull/41337) for updating the package in the Gutenberg repository, so I'll start merging these changes as soon as possible.

**Pull request merged**
