### PR TITLE
Upgrade Gradle to 7.4 & AGP to 7.1.1 (& Disable Jetifier)

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR is part of [Upgrade Gradle to 7.4 & AGP to 7.1.1 (& Disable Jetifier)](https://github.com/WordPress/gutenberg/pull/39097) PR. There are `13` libraries that are upgraded to `Gradle 7.4` & `AGP 7.1.1` (& `Disable Jetifier`).

-----

All those PRs follow the general outline below:
- `Gradle` version upgraded to `7.3.3` with the `./gradlew wrapper --gradle-version=7.3.3 --distribution-type=all` command.
- `AGP` version upgrade to `7.0.4` (see `android/settings.gradle.kts` change).
- Build output diff:
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- Lint output diff
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- The above 4 steps were redone with a follow-up update to `Gradle 7.4` & `AGP 7.1.1`.
- Jetifier drop (see `android/gradle.properties` change).
- **OUTDATED** ❌
  - Version bump to `1.10.1-wp-5` (see `package.json`).
  - Tarball update to `1.10.1-wp-5` (see `react-native-gesture-handler-1.10.1-wp-5.tgz`).
  - The build was also verified through [Jitpack](https://jitpack.io/#wordpress-mobile/react-native-gesture-handler) (see [build.log](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/3216e18848/build.log)).
- **OUTDATED** ❌
  - `AGP` version upgrade to `7.1.1` (from `4.1.0`) (within `android/build.gradle`). Cc @oguzkocer
  - Version bump to `2.2.0-wp-4` (see `package.json`).
  - Tarball update to `2.2.0-wp-4` (see `react-native-gesture-handler-2.2.0-wp-4.tgz`).
  - The build was also verified through [Jitpack](https://jitpack.io/#wordpress-mobile/react-native-gesture-handler) (see [build.log](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/1bd872fcd9/build.log)).
- **UPDATED** ✅
  - Use common interface from reanimated (for more deals see [here](https://github.com/WordPress/gutenberg/pull/39097#issuecomment-1068269280)).
  - Version bump to `2.2.0-wp-5` (see `package.json`).
  - Tarball update to `2.2.0-wp-5` (see `react-native-gesture-handler-2.2.0-wp-5.tgz`).
  - The build was also verified through [Jitpack](https://jitpack.io/#wordpress-mobile/react-native-gesture-handler) (see [build.log](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/aa2bbc9680/build.log)).

-----

**To test - Now**

These changes can be tested as part of the [gutenberg PR](https://github.com/WordPress/gutenberg/pull/39097) which is [updated to use the temporarily non-tagged node module project dependencies](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56) generated with these changes.

**To test - Later** ⚙️

These changes can be tested as part of the [gutenberg-mobile PR ⚙️](TODO) or [WordPress-Android PR ⚙️](TODO) which is [updated to use the bundle ⚙️](TODO) generated with these changes.

FYI: It's best to leave the testing step to the [gutenberg PR](https://github.com/WordPress/gutenberg/pull/39097) review since even if these PRs are merged, they won't impact anything until [the package.json file is updated](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56). Worst case scenario, a follow up PR will get opened to fix any issues that are found during testing.

-----

**Follow up**

Once these PRs are merged in, a new tag will get created for each library and [the package.json file will be again updated accordingly](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56).

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]

**Comment by ParaskP7** [comment]
👋 @oguzkocer 

> AGP version upgrade to 7.1.1 (from 4.1.0) (within android/build.gradle). Cc @oguzkocer

You will notice that I cc'ed you on the description because I want you to be aware of this change since it might revert the change you did by creating `settings.gradle.kts` and using `pluginManagement` instead of doing that directly through `buildscript`. Wdyt?

PS: This change was done because the `wp-fork` was recently updated from `1.10.1-wp-4` to `2.2.0-wp-3`, a major upgrade on this branch, lots of diffs, which I then pulled in this PR to keep it up-to-date. Cc @fluiddot

**Comment by oguzkocer** [comment]
@ParaskP7 I've added plugin DSL support to this project as well as many other `react-native` fork projects because I wanted `react-native-bridge` the ability to set the plugin version for easy testing. In my humble opinion reverting the change is counter-productive and 71885ee65cdfea40b17946768d2042f4e3c4dec5 by @fluiddot was a mistake.

@fluiddot The merge conflict was a very easy one to address, so I was wondering why you have opted to make this change. Is it at all possible you weren't familiar with the plugin DSL? If so, we can fix that easily in this PR. However, if it was intentional, I hope we can discuss it before we commit to the version in this PR.

**Comment by fluiddot** [comment]
> @fluiddot The merge conflict was a very easy one to address, so I was wondering why you have opted to make this change. Is it at all possible you weren't familiar with the plugin DSL? If so, we can fix that easily in this PR. However, if it was intentional, I hope we can discuss it before we commit to the version in this PR.

Just to clarify, do you refer to the change in the `plugins` block?

**Before:**
```
plugins {
    id "com.android.library"
    id "kotlin-android"
    id "maven-publish"
}
```

**After:**
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'
```

If so, it was probably a mistake from my side. I'm still getting familiar with Gradle DSL, so please let me know if there's anything else incorrect in the configurations 🙇 .

**Comment by oguzkocer** [comment]
@fluiddot That's part of it, but in short, we shouldn't have a `buildscript` block which is the old notation. For example, `classpath("com.android.tools.build:gradle:4.1.0")` is not necessary, because the version is set in the `settings.gradle.kts` [like so](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/5/files#diff-b846529d3b9af5e34dfb0174742f9dc3d52bcd97761555bc61271a7a868870b9R3). Kotlin plugin declaration should also be done in the `settings.gradle.kts` file similar [to this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/settings.gradle#L6-L9).

Hope that clarifies it and if you'd like to learn more about the plugin DSL, you might find [this documentation](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) useful.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @fluiddot That's part of it, but in short, we shouldn't have a buildscript block which is the old notation. For example, classpath("com.android.tools.build:gradle:4.1.0") is not necessary, because the version is set in the settings.gradle.kts [like so](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/5/files#diff-b846529d3b9af5e34dfb0174742f9dc3d52bcd97761555bc61271a7a868870b9R3). Kotlin plugin declaration should also be done in the settings.gradle.kts file similar [to this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/settings.gradle#L6-L9).

Can you please take a look at this a00be9157b6c1ac100f516f487967a6e4e3b6ce3 commit, which resolves the above, and verify that I am not missing anything? 🙇 

Cc @fluiddot

**Comment by oguzkocer** [comment]
@ParaskP7 a00be9157b6c1ac100f516f487967a6e4e3b6ce3 looks good to me, although I'd have preferred it if we passed the kotlin version directly instead of relying on a property. In `settings.gradle` files, using properties can be tricky at times. If it's working as is though, I don't mind keeping it if you prefer it like this.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @ParaskP7 https://github.com/wordpress-mobile/react-native-gesture-handler/commit/a00be9157b6c1ac100f516f487967a6e4e3b6ce3 looks good to me, although I'd have preferred it if we passed the kotlin version directly instead of relying on a property. In settings.gradle files, using properties can be tricky at times. If it's working as is though, I don't mind keeping it if you prefer it like this.

Thanks for your input, I only chose this way in order to minimize changes from upstream. To be honest I am also preferring if we passed the Kotlin version directly. But yes, it does work as expected. 👍 

@fluiddot wdyt, should I do this change or do you prefer us staying as close to the upstream as possible? 🤔

**Comment by fluiddot** [comment]
> @fluiddot wdyt, should I do this change or do you prefer us staying as close to the upstream as possible? 🤔

@ParaskP7 Both options work for me, as we're already applying several modifications to the project, making more shouldn't be a problem.

If I understand correctly, the change would be to remove `RNGH_kotlinVersion=1.5.20` from `android/gradle.properties` and set the version directly in `android/settings.gradle.kts`, right? In that case, I think the change is minor so feel free to apply it.

**Comment by ParaskP7** [comment]
👋 @fluiddot !

> @ParaskP7 Both options work for me, as we're already applying several modifications to the project, making more shouldn't be a problem.

Thanks for your input! 👍 

> If I understand correctly, the change would be to remove RNGH_kotlinVersion=1.5.20 from android/gradle.properties and set the version directly in android/settings.gradle.kts, right?

Exactly! 👍 

> In that case, I think the change is minor so feel free to apply it.

On it! 👍

**Comment by fluiddot** [comment]
@ParaskP7 Heads up that I've updated this branch with the recent changes incorporated in `wp-fork` ([reference](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/18)) and generated a new tarball. Besides, I also updated the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/39097) to reflect the new version.

**Comment by ParaskP7** [comment]
👋 @fluiddot !

> @ParaskP7 Heads up that I've updated this branch with the recent changes incorporated in wp-fork (https://github.com/wordpress-mobile/react-native-gesture-handler/pull/18) and generated a new tarball. Besides, I also updated the https://github.com/WordPress/gutenberg/pull/39097 to reflect the new version.

Thanks for this update! 👍 

Btw, I just triggered a Jitpack build based on the latest commit and I got a build failure (see [here](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/9aa0bb5414/build.log)).

`TIL`
```
* What went wrong:
Execution failed for task ':generateDebugRFile'.
> Could not resolve all files for configuration ':debugCompileClasspath'.
   > Could not find com.github.wordpress-mobile:react-native-reanimated:2.4.1-wp-1.
     Required by:
         project :
```

**Comment by ParaskP7** [comment]
**UPDATE**: @fluiddot after your latest [merge commit](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/12/commits/9969908f9724d7eda4c5a0a50d60565bbf1ab01b) the build is now successful (see [here](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/9969908f97/build.log)).

PS: Should we also generate a new tarball as well? 🤔

**Comment by fluiddot** [comment]
> Btw, I just triggered a Jitpack build based on the latest commit and I got a build failure (see [here](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/9aa0bb5414/build.log)).

Yep, sorry for that, I forgot to add Jitpack repository, which was required for the latest changes.

> **UPDATE**: @fluiddot after your latest [merge commit](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/12/commits/9969908f9724d7eda4c5a0a50d60565bbf1ab01b) the build is now successful (see [here](https://jitpack.io/com/github/wordpress-mobile/react-native-gesture-handler/9969908f97/build.log)).
> 
> PS: Should we also generate a new tarball as well? 🤔

Right, I've just updated the tarball in https://github.com/wordpress-mobile/react-native-gesture-handler/pull/12/commits/aa2bbc9680dd0ed4e0bb57d51614e0aa530a1ef7.

**Comment by ParaskP7** [comment]
Since we removed the source code for these projects from `react-native-bridge`, we don’t need these updates to happen together with the other projects anymore. That means we can close this draft PR for now and reopen it, if need be, in the future. There is little value in merging this now and diverging from the source repo.

PS: Eventually, we might upgrade `Gradle & AGP` when using a newer version of `React Native` if the new RN version requires it.

**Pull request closed without merging**
